 <!DOCTYPE html>
 <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Blank Page</title>
        <meta name="description" content="Metis: Bootstrap Responsive Admin Theme">
        <meta name="viewport" content="width=device-width">
        <link type="text/css" rel="stylesheet" href="<?php print PUBLIC_F ?>/css/bootstrap.min.css"/>
        <link type="text/css" rel="stylesheet" href="<?php print PUBLIC_F ?>/css/bootstrap-responsive.min.css"/>
        <link type="text/css" rel="stylesheet" href="<?php print PUBLIC_F ?>/Font-awesome/css/font-awesome.min.css"/>
        <link type="text/css" rel="stylesheet" href="<?php print PUBLIC_F ?>/css/style.css"/>
        
        <link rel="stylesheet" href="<?php print PUBLIC_F ?>/css/theme.css">
	
        <script type="text/javascript" src="<?php print PUBLIC_F ?>/js/vendor/modernizr-2.6.2-respond-1.1.0.min.js"></script>
        <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
        <!--[if IE 7]>
        <link type="text/css" rel="stylesheet" href="assets/Font-awesome/css/font-awesome-ie7.min.css"/>
        <![endif]-->
</head>
<body>
	  <div id="wrap">
